# Site settings
title: My Radical Website
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
facebook: "/assets/img/fb.png" #facebook icon path
twitter: "/assets/img/twitter.png" #twitter icon path
instagram: "/assets/img/instagram.png" #instagram icon path

# Build settings
markdown: kramdown
